application:
  app_name: "Save/get shares service"
  app_version: "0.1.1"

kafka_share_reader:
  brokers:
    - "127.0.0.1:9092"
  group: "sharesGroup"
  topic: "shares"
  auto_commit_enable: true
  auto_commit_interval: 5

kafka_metric_writer:
  brokers:
    - "127.0.0.1:9092"
  topic: "shares"

grpc:
  coin_target: "127.0.0.1:17878"
  miner_target: "127.0.0.1:17878"
  shares_target: "127.0.0.1:6878"

auth:
  jwt_service_name: "normalizer"
  jwt_secret: "jwtsecret"
  jwt_valid_services:
    - "normalizer"
    - "timeseries"

